In [3]:
# Import pandas library
import pandas as pd

# Load the CSV file into a DataFrame (adjust path if file is not in the current directory)
df = pd.read_csv('D:\SHE CARES\Menstural_cyclelength.csv')

# Display the first 5 rows of the dataset
df.head()

,new_id,age,cycle_number,cycle_start_date,cycle_end_date,cycle_length,conception_cycle
0,1,26,1,5/21/03,6/16/03,0,No
1,1,26,2,6/17/03,7/15/03,0,No
2,1,26,3,7/16/03,8/13/03,0,Yes
3,2,28,2,06-09-2003,07-05-2003,0,No
4,2,28,3,07-06-2003,08-09-2003,0,Yes

In [4]:
# Check for missing values in each column
missing_per_column = df.isnull().sum()

# Check total missing values in the dataset
total_missing = missing_per_column.sum()

# Print missing values info
print("Missing values per column:")
print(missing_per_column)
print(f"\nTotal missing values in dataset: {total_missing}")

if total_missing == 0:
    print("\nDataset is clean with no missing values.")
else:
    print("\nDataset has missing values that need to be filled.")

Missing values per column:
new_id              0
age                 0
cycle_number        0
cycle_start_date    0
cycle_end_date      0
cycle_length        0
conception_cycle    0
dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [1]:
# Import pandas library
import pandas as pd

# Load the CSV file into a DataFrame (adjust path if file is not in the current directory)
df = pd.read_csv('D:\SHE CARES\Maternal Health Risk Data Set.csv')

# Display the first 5 rows of the dataset
df.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [2]:
# Check for missing values in each column
missing_per_column = df.isnull().sum()

# Check total missing values in the dataset
total_missing = missing_per_column.sum()

# Print missing values info
print("Missing values per column:")
print(missing_per_column)
print(f"\nTotal missing values in dataset: {total_missing}")

if total_missing == 0:
    print("\nDataset is clean with no missing values.")
else:
    print("\nDataset has missing values that need to be filled.")

Missing values per column:
Age            0
SystolicBP     0
DiastolicBP    0
BS             0
BodyTemp       0
HeartRate      0
RiskLevel      0
dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [2]:
# Import pandas library
import pandas as pd

# Load the CSV file into a DataFrame (adjust path if file is not in the current directory)
df = pd.read_csv('D:\SHE CARES\Maternal Health Risk Data Set.csv')

# Display the first 5 rows of the dataset
df.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [3]:
# Check for missing values in each column
missing_per_column = df.isnull().sum()

# Check total missing values in the dataset
total_missing = missing_per_column.sum()

# Print missing values info
print("Missing values per column:")
print(missing_per_column)
print(f"\nTotal missing values in dataset: {total_missing}")

if total_missing == 0:
    print("\nDataset is clean with no missing values.")
else:
    print("\nDataset has missing values that need to be filled.")

Missing values per column:
Age            0
SystolicBP     0
DiastolicBP    0
BS             0
BodyTemp       0
HeartRate      0
RiskLevel      0
dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [6]:
import pandas as pd
df=pd.read_csv('D:\SHE CARES\FedCycleData071012.csv')
df.head()

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,

In [7]:
# Check for missing values in each column
missing_per_column = df.isnull().sum()

# Check total missing values in the dataset
total_missing = missing_per_column.sum()

# Print missing values info
print("Missing values per column:")
print(missing_per_column)
print(f"\nTotal missing values in dataset: {total_missing}")

if total_missing == 0:
    print("\nDataset is clean with no missing values.")
else:
    print("\nDataset has missing values that need to be filled.")

Missing values per column:
ClientID                0
CycleNumber             0
Group                   0
CycleWithPeakorNot      0
ReproductiveCategory    0
                       ..
NextpregM               0
Spousesame              0
SpousesameM             0
Timeattemptpreg         0
BMI                     0
Length: 80, dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [11]:
import pandas as pd
df=pd.read_csv('D:/SHE CARES/PCOS_infertility.csv')
df.head()

,Sl. No,Patient File No.,PCOS (Y/N),I beta-HCG(mIU/mL),II beta-HCG(mIU/mL),AMH(ng/mL)
0,1,10001,0,1.99,1.99,2.07
1,2,10002,0,60.80,1.99,1.53
2,3,10003,1,494.08,494.08,6.63
3,4,10004,0,1.99,1.99,1.22
4,5,10005,0,801.45,801.45,2.26

In [12]:
# Check for missing values in each column
missing_per_column = df.isnull().sum()

# Check total missing values in the dataset
total_missing = missing_per_column.sum()

# Print missing values info
print("Missing values per column:")
print(missing_per_column)
print(f"\nTotal missing values in dataset: {total_missing}")

if total_missing == 0:
    print("\nDataset is clean with no missing values.")
else:
    print("\nDataset has missing values that need to be filled.")

Missing values per column:
Sl. No                    0
Patient File No.          0
PCOS (Y/N)                0
  I   beta-HCG(mIU/mL)    0
II    beta-HCG(mIU/mL)    0
AMH(ng/mL)                0
dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [18]:
import pandas as pd
df=pd.read_excel('D:/SHE CARES/PCOS_data_without_infertility.xlsx')
df.head()

,Instructions to be followed :,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,1.0,Kindly ensure that the datas are converted to...,NaN,NaN
2,2.0,Please fill up the entire data set of a patient,NaN,NaN
3,3.0,Manipulated datas if any need to be highlighte...,NaN,NaN
4,4.0,"For every Yes/No questions *** , Indicate Yes...",NaN,NaN

In [34]:
# Check for missing values in each column
missing_per_column = df.isnull().sum()

# Check total missing values in the dataset
total_missing = missing_per_column.sum()

# Print missing values info
print("Missing values per column:")
print(missing_per_column)
print(f"\nTotal missing values in dataset: {total_missing}")

if total_missing == 0:
    print("\nDataset is clean with no missing values.")
else:
    print("\nDataset has missing values that need to be filled.")

Missing values per column:
Instructions to be followed :    0
Unnamed: 1                       0
Unnamed: 2                       0
Unnamed: 3                       0
dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [35]:
import pandas as pd

# Load the Excel file
df = pd.read_excel('D:/SHE CARES/PCOS_data_without_infertility.xlsx')

# Print missing values by column before filling
print("Missing values before filling:")
print(df.isnull().sum())

# Fill missing numeric values with median of each column
df['Unnamed: 2'].fillna('Unknown', inplace=True)


# Fill missing non-numeric (object) columns optionally, e.g., with mode
for col in df.select_dtypes(include=['object']).columns:
    mode = df[col].mode()
    if not mode.empty:
        df.loc[:, col] = df[col].fillna(mode[0])


# Print missing values after filling
print("\nMissing values after filling:")
print(df.isnull().sum())

# Save the cleaned data back to Excel
df.to_excel('D:/SHE CARES/PCOS_data_without_infertility.xlsx', index=False)

Missing values before filling:
Instructions to be followed :    0
Unnamed: 1                       0
Unnamed: 2                       0
Unnamed: 3                       0
dtype: int64

Missing values after filling:
Instructions to be followed :    0
Unnamed: 1                       0
Unnamed: 2                       0
Unnamed: 3                       0
dtype: int64

C:\Users\user\AppData\Local\Temp\ipykernel_30060\3464005136.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Unnamed: 2'].fillna('Unknown', inplace=True)

In [36]:
# Check for missing values in each column
missing_per_column = df.isnull().sum()

# Check total missing values in the dataset
total_missing = missing_per_column.sum()

# Print missing values info
print("Missing values per column:")
print(missing_per_column)
print(f"\nTotal missing values in dataset: {total_missing}")

if total_missing == 0:
    print("\nDataset is clean with no missing values.")
else:
    print("\nDataset has missing values that need to be filled.")

Missing values per column:
Instructions to be followed :    0
Unnamed: 1                       0
Unnamed: 2                       0
Unnamed: 3                       0
dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [37]:
import pandas as pd
df=pd.read_csv('D:/SHE CARES/post natal data.csv')
df.head()

,Timestamp,Age,Feeling sad or Tearful,Irritable towards baby & partner,Trouble sleeping at night,Problems concentrating or making decision,Overeating or loss of appetite,Feeling anxious,Feeling of guilt,Problems of bonding with baby,Suicide attempt
0,6/14/2022 20:02,35-40,Yes,Yes,Two or more days a week,Yes,Yes,Yes,No,Yes,Yes
1,6/14/2022 20:03,40-45,Yes,No,No,Yes,Yes,No,Yes,Yes,No
2,6/14/2022 20:04,35-40,Yes,No,Yes,Yes,Yes,Yes,No,Sometimes,No
3,6/14/2022 20:05,35-40,Yes,Yes,Yes,Yes,No,Yes,Maybe,No,No
4,6/14/2022 20:06,40-45,Yes,No,Two or more days a week,Yes,No,Yes,No,Yes,No

In [46]:
# Check for missing values in each column
import pandas as pd
df=pd.read_excel('D:/SHE CARES/PCOS_data_without_infertility.xlsx')
df.head()

Missing values per column:
Timestamp                                    0
Age                                          0
Feeling sad or Tearful                       0
Irritable towards baby & partner             0
Trouble sleeping at night                    0
Problems concentrating or making decision    0
Overeating or loss of appetite               0
Feeling anxious                              0
Feeling of guilt                             0
Problems of bonding with baby                0
Suicide attempt                              0
dtype: int64

Total missing values in dataset: 0

Dataset is clean with no missing values.

In [45]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('D:/SHE CARES/post natal data.csv')

# Fill missing numeric columns with median
df.fillna(df.median(numeric_only=True), inplace=True)

# Fill missing categorical columns with mode
for col in df.select_dtypes(include=['object']).columns:
    mode = df[col].mode()
    if not mode.empty:
        df.loc[:, col] = df[col].fillna(mode[0])

# Verify no missing values remain
print(df.isnull().sum())

# Save the cleaned data back to Excel
df.to_excel('D:/SHE CARES/PCOS_data_without_infertility.xlsx', index=False)

Timestamp                                    0
Age                                          0
Feeling sad or Tearful                       0
Irritable towards baby & partner             0
Trouble sleeping at night                    0
Problems concentrating or making decision    0
Overeating or loss of appetite               0
Feeling anxious                              0
Feeling of guilt                             0
Problems of bonding with baby                0
Suicide attempt                              0
dtype: int64

In [1]:

import pandas as pd
df=pd.read_csv('D:/SHE CARES/PCOS_data.csv')
df.head()

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm),Unnamed: 44
0,1,1,0,28,44.6,152.0,19.3,15,78,22,...,1.0,0,110,80,3,3,18.0,18.0,8.5,NaN
1,2,2,0,36,65.0,161.5,24.9,15,74,20,...,0.0,0,120,70,3,5,15.0,14.0,3.7,NaN
2,3,3,1,33,68.8,165.0,25.3,11,72,18,...,1.0,0,120,80,13,15,18.0,20.0,10.0,NaN
3,4,4,0,37,65.0,148.0,29.7,13,72,20,...,0.0,0,120,70,2,2,15.0,14.0,7.5,NaN
4,5,5,0,25,52.0,161.0,20.1,11,72,18,...,0.0,0,120,80,3,4,16.0,14.0,7.0,NaN

In [2]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('D:/SHE CARES/post natal data.csv')

# Fill missing numeric columns with median
df.fillna(df.median(numeric_only=True), inplace=True)

# Fill missing categorical columns with mode
for col in df.select_dtypes(include=['object']).columns:
    mode = df[col].mode()
    if not mode.empty:
        df.loc[:, col] = df[col].fillna(mode[0])

# Verify no missing values remain
print(df.isnull().sum())

# Save the cleaned data back to Excel
df.to_excel('D:/SHE CARES/PCOS_data_without_infertility.xlsx', index=False)

Sl. No                    0
Patient File No.          0
PCOS (Y/N)                0
 Age (yrs)                0
Weight (Kg)               0
Height(Cm)                0
BMI                       0
Blood Group               0
Pulse rate(bpm)           0
RR (breaths/min)          0
Hb(g/dl)                  0
Cycle(R/I)                0
Cycle length(days)        0
Marraige Status (Yrs)     0
Pregnant(Y/N)             0
No. of abortions          0
  I   beta-HCG(mIU/mL)    0
II    beta-HCG(mIU/mL)    0
FSH(mIU/mL)               0
LH(mIU/mL)                0
FSH/LH                    0
Hip(inch)                 0
Waist(inch)               0
Waist:Hip Ratio           0
TSH (mIU/L)               0
AMH(ng/mL)                0
PRL(ng/mL)                0
Vit D3 (ng/mL)            0
PRG(ng/mL)                0
RBS(mg/dl)                0
Weight gain(Y/N)          0
hair growth(Y/N)          0
Skin darkening (Y/N)      0
Hair loss(Y/N)            0
Pimples(Y/N)              0
Fast food (Y/N)           0
Reg.Exercise(Y/N)         0
BP _Systolic (mmHg)       0
BP _Diastolic (mmHg)      0
Follicle No. (L)          0
Follicle No. (R)          0
Avg. F size (L) (mm)      0
Avg. F size (R) (mm)      0
Endometrium (mm)          0
Unnamed: 44               0
dtype: int64